---
- name: Installing Packages for Python-MySQL for Debian
  apt:
    name: "{{ item.pkg_name }}"
    state: present
  with_items: "{{ debian_package_Python_MySQL }}"
  when: ansible_distribution == 'Ubuntu'

- name: Set root user password
  mysql_user:
    name: root
    password: "{{ mysql_root_password}}"
    check_implicit_admin: true

- name: Add config file
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0600

- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user: 
    user: ""
    host: "{{ ansible_fqdn }}"
    state: absent

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user: 
    user: root
    password: "{{ mysql_root_password }}" 
    host: "{{ item }}"
  with_items:
     - 127.0.0.1
     - localhost
     - "{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db: 
    db: test 
    state: absent

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  notify:
    - Restarting MySQL

